# Generated by Django 5.2.9 on 2025-12-27 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inactive_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inactiveuserlog',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inactiveuserlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
