# Generated by Django 6.0 on 2025-12-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={},
        ),
    ]
