# Generated by Django 5.2.9 on 2026-01-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_courseprogress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
