# Generated by Django 5.2.10 on 2026-01-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_courseprogress_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
