# Generated by Django 5.2.10 on 2026-01-22 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_content', '0002_lessoncontent_article_pdf_alter_lesson_id_and_more'),
        ('courses', '0002_alter_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContentLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('mixed', 'Mixed')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course_content_lesson',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.CreateModel(
            name='CourseContentLessonContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('article_text', models.TextField(blank=True, null=True)),
                ('article_pdf', models.FileField(blank=True, null=True, upload_to='lesson_pdfs/')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='course_content.coursecontentlesson')),
            ],
            options={
                'db_table': 'course_content_lessoncontent',
            },
        ),
        migrations.CreateModel(
            name='CourseContentSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='courses.course')),
            ],
            options={
                'db_table': 'course_content_section',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='coursecontentlesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_content.coursecontentsection'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonContent',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
